language: php

services:
    - docker

before_install:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    - echo "ADD . /var/www/docker-symfony" >> Dockerfile
    - docker build --no-cache -t sskorc/docker-symfony-dist .
    - docker tag sskorc/docker-symfony-dist:latest sskorc/docker-symfony-dist:$TRAVIS_BUILD_NUMBER
    - docker push sskorc/docker-symfony-dist
