language: php

install: echo "party time"

script: echo "like it's cat meow 99" && true

before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
      - provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        local_dir: dpl_cd_upload
        skip_cleanup: true
        bucket: docker-symfony
      - provider: codedeploy
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: docker-symfony
        key: latest.zip
        bundle_type: zip
        application: docker-symfony
        deployment_group: docker-symfony
