FROM sskorc/symfony2-mongo:latest

ADD docker/php.ini /usr/local/etc/php/php.ini
ADD docker/vhost.conf /etc/nginx/conf.d/default.conf
ADD . /var/www/docker-symfony

RUN /var/www/docker-symfony/startup.sh

WORKDIR /var/www/docker-symfony
